name: export-updates
on:
  push:
    branches: [ master ]

jobs: 
  deploy:
    environment: deploy
    runs-on: ubuntu-latest
    env:
      DEPLOY_HOST: ${{ secrets.SERVER_HOST }}
      DEPLOY_USER: ${{ secrets.SERVER_USER }}
      QILI_APP: parrot
      QILI_UPDATES: updates
      production: true
    steps:
    - run: sudo apt-get install -y sshpass
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: build www
      run: |
        cd www
        yarn
        yarn global add npx
        yarn build
    - name: deploy cloud code to qili2
      run: | 
          export SSHPASS=${{ secrets.SERVER_PASS }}
          sshpass -p "$SSHPASS" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $DEPLOY_USER@$DEPLOY_HOST "rm -rf /data/apps/bridge/www 2>/dev/null"
          sshpass -p "$SSHPASS" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $DEPLOY_USER@$DEPLOY_HOST "mkdir -p /data/apps/bridge/www"
          sshpass -e scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r www/web-build/* "$DEPLOY_USER@$DEPLOY_HOST:/data/apps/bridge/www"
          sshpass -e scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null package.json "$DEPLOY_USER@$DEPLOY_HOST:/data/apps/bridge"
          sshpass -e scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null index.js "$DEPLOY_USER@$DEPLOY_HOST:/data/apps/bridge"
          sshpass -e scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null qili.conf.js "$DEPLOY_USER@$DEPLOY_HOST:/data/apps/bridge"
          sshpass -e scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null yarn.lock "$DEPLOY_USER@$DEPLOY_HOST:/data/apps/bridge"
          sshpass -e scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null nginx.conf "$DEPLOY_USER@$DEPLOY_HOST:/data/apps/bridge"
          sshpass -e ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "./qili.travis.deploy.sh"